# Generated by Django 4.0.3 on 2022-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(default='default value', max_length=50)),
                ('last_name', models.CharField(default='default value', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/emp')),
                ('project', models.CharField(choices=[('RD', 'roadhow'), ('CL', 'clara'), ('AV', 'avdevs'), ('SA', 'streetai'), ('9F', '9tofive')], default='default value', max_length=100)),
            ],
        ),
    ]
